name: Price_bot CI/CD

on:
  push:
    branches:
      - price_bot_develop
  # pull_request:
  #   branches:
  #     - price_bot_develop

jobs:
    install:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        # - name: Run tests
        #   run: |
        #     # Добавьте команду для запуска тестов, если они есть
        #     pytest  # Если используете pytest, замените на свою команду тестирования
    tests:
      runs-on: ubuntu-latest
      needs: install
      steps:
      - name: Test with flake8
        run: |
          pip install flake8 pep8-naming flake8-broken-line flake8-return
          python -m flake8

    build_and_push_to_docker_hub:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        needs: tests
        steps:
        - name: Build Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/price_bot:latest .

        - name: Push Docker image
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker push ${{ secrets.DOCKER_USERNAME }}/price_bot:latest

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build_and_push_to_docker_hub  # Деплой происходит после успешного билда
    #     steps:
    #       - name: Deploy to server
    #         uses: appleboy/ssh-action@v0.1.3  # Используем экшн для SSH подключения
    #         with:
    #           host: ${{ secrets.SERVER_HOST }}  # IP или доменное имя сервера
    #           username: ${{ secrets.SERVER_USER }}  # Пользователь на сервере
    #           key: ${{ secrets.SERVER_SSH_KEY }}  # Приватный ключ для SSH доступа
    #           port: 22  # Порт SSH
    #           script: |
    #             docker pull your_docker_username/your_image_name  # Загружаем новый образ
    #             docker stop your_container_name || true  # Останавливаем старый контейнер
    #             docker rm your_container_name || true  # Удаляем старый контейнер
    #             docker run -d --name your_container_name -p 80:80 your_docker_username/your_image_name  # Запускаем новый контейнер          