version: '2'
services:
    web:
        build: .
        ports:
            - "18001:5000"
        volumes:
            - .:/code
#        depends_on:
#            - redis
        restart: always
#    redis:
#        image: redis
#        restart: always