name: StudyDeployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PATH_INPUT: .
  PATH_OUTPUT: /home/dev_stand/team22
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Deploy to Server # copy all repo files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STUDY_DEPLOY_SERVER_HOST }}
          port: ${{ secrets.STUDY_DEPLOY_SERVER_PORT }}
          username: ${{ secrets.STUDY_DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.STUDY_DEPLOY_SERVER_KEY }}
          source: ${{ env.PATH_INPUT }}
          target: ${{ env.PATH_OUTPUT }}
          strip_components: 1

      - name: d-c stop start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STUDY_DEPLOY_SERVER_HOST }}
          username: ${{ secrets.STUDY_DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.STUDY_DEPLOY_SERVER_KEY }}
          port: ${{ secrets.STUDY_DEPLOY_SERVER_PORT }}
          script: |
            cd ${{ env.PATH_OUTPUT }}/library/projects/Price_bot
            sudo docker-compose stop
            sudo docker-compose rm bot
            rm .env
            touch .env
            echo BOT_TOKEN=7843933472:AAFdOEasiDy6rA_mPfW3_eCB4q4tmsUotwU >> .env
            sudo docker-compose up -d

      # - name: Print Info SimpleKanban
      #   run: echo "Deployed SimpleKanban at http://absda.ru:31001"
      # - name: Print Info teleban
      #   run: echo "Deployed teleban at http://absda.ru:31003"
      - name: Print Info Price_bot
        run: echo "Deployed Price_bot at http://absda.ru:31002"
