name: TeleBAN Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PATH_INPUT: .
  PATH_OUTPUT: /home/dev_stand/team22

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STUDY_DEPLOY_SERVER_HOST }}
          port: ${{ secrets.STUDY_DEPLOY_SERVER_PORT }}
          username: ${{ secrets.STUDY_DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.STUDY_DEPLOY_SERVER_KEY }}
          source: ${{ env.PATH_INPUT }}
          target: ${{ env.PATH_OUTPUT }}
          strip_components: 1

      - name: Restart Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STUDY_DEPLOY_SERVER_HOST }}
          username: ${{ secrets.STUDY_DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.STUDY_DEPLOY_SERVER_KEY }}
          port: ${{ secrets.STUDY_DEPLOY_SERVER_PORT }}
          script: |
            cd ${{ env.PATH_OUTPUT }}/library/projects/teleban
            rm .env
            
            touch .env
            echo TELEBAN_TOKEN = ${{ secrets.TELEBAN_TOKEN }} >> .env
            echo DB_HOST = ${{ secrets.TELEBAN_DB_HOST }} >> .env
            echo DB_PORT = ${{ secrets.TELEBAN_DB_PORT }} >> .env
            echo DB_NAME = ${{ secrets.TELEBAN_DB_NAME }} >> .env
            echo DB_USER = ${{ secrets.TELEBAN_DB_USER }} >> .env
            echo DB_PASS = ${{ secrets.TELEBAN_DB_PASS }} >> .env
            
            docker-compose down --rmi all
            docker-compose up --build -d

      - name: Print Info teleban
        run: echo "Deployed teleban at http://absda.ru:31003"
